import { PixelGrid } from './PixelGrid'
import { Portrait } from './Portrait'

export type IconName =
  | 'face'
  | 'hd'
  | 'folder'
  | 'doc'
  | 'trash'
  | 'work'
  | 'star'
  | 'terminal'
  | 'mail'
  | 'note'
  | 'people'
  | 'bomb'

// '#' ink, 'a' accent (the fill prop), 'o' paper, 'k' screen black, 'g' screen green
const GRIDS: Record<Exclude<IconName, 'face'>, string[]> = {
  hd: [
    '................',
    '................',
    '.##############.',
    '#aaaaaaaaaaaaaa#',
    '#aaaaaaaaaaaaaa#',
    '#aaaaaaaaaaaaaa#',
    '#aaaaaaaaaaaaaa#',
    '#aaaaaaaaaaaaaa#',
    '#aaaaaaaaaaaaaa#',
    '#aaaaaaaaaaaaaa#',
    '################',
    '#oooooooooooooo#',
    '#o##oooooo####o#',
    '#oooooooooooooo#',
    '.##############.',
    '................',
  ],
  folder: [
    '................',
    '................',
    '.#####..........',
    '#aaaaa#.........',
    '#aaaaaa########.',
    '#aaaaaaaaaaaaaa#',
    '#aaaaaaaaaaaaaa#',
    '#aaaaaaaaaaaaaa#',
    '#aaaaaaaaaaaaaa#',
    '#aaaaaaaaaaaaaa#',
    '#aaaaaaaaaaaaaa#',
    '#aaaaaaaaaaaaaa#',
    '#aaaaaaaaaaaaaa#',
    '.##############.',
    '................',
    '................',
  ],
  doc: [
    '..#########.....',
    '..#aaaaaaa##....',
    '..#aaaaaaa#o#...',
    '..#aaaaaaa####..',
    '..#aaaaaaaaaa#..',
    '..#a########a#..',
    '..#aaaaaaaaaa#..',
    '..#a########a#..',
    '..#aaaaaaaaaa#..',
    '..#a########a#..',
    '..#aaaaaaaaaa#..',
    '..#a#####aaaa#..',
    '..#aaaaaaaaaa#..',
    '..#aaaaaaaaaa#..',
    '..############..',
    '................',
  ],
  trash: [
    '................',
    '.....######.....',
    '..############..',
    '..#aaaaaaaaaa#..',
    '..############..',
    '...#aaaaaaaa#...',
    '...#a#a##a#a#...',
    '...#a#a##a#a#...',
    '...#a#a##a#a#...',
    '...#a#a##a#a#...',
    '...#a#a##a#a#...',
    '...#a#a##a#a#...',
    '...#aaaaaaaa#...',
    '...##########...',
    '................',
    '................',
  ],
  work: [
    '................',
    '................',
    '.....######.....',
    '.....#....#.....',
    '.##############.',
    '#aaaaaaaaaaaaaa#',
    '#aaaaaaaaaaaaaa#',
    '#aaaaaaaaaaaaaa#',
    '################',
    '#aaaaaa##aaaaaa#',
    '#aaaaaa##aaaaaa#',
    '#aaaaaaaaaaaaaa#',
    '#aaaaaaaaaaaaaa#',
    '.##############.',
    '................',
    '................',
  ],
  star: [
    '................',
    '.......##.......',
    '.......##.......',
    '......#aa#......',
    '......#aa#......',
    '.#####aaaa#####.',
    '.#aaaaaaaaaaaa#.',
    '..#aaaaaaaaaa#..',
    '...#aaaaaaaa#...',
    '....#aaaaaa#....',
    '....#aaaaaa#....',
    '...#aaa##aaa#...',
    '...#aa#..#aa#...',
    '..#a##....##a#..',
    '..##........##..',
    '................',
  ],
  terminal: [
    '................',
    '.##############.',
    '#aaaaaaaaaaaaaa#',
    '################',
    '#kkkkkkkkkkkkkk#',
    '#kkgkkkkkkkkkkk#',
    '#kkkgkkkkkkkkkk#',
    '#kkkkgkkkkkkkkk#',
    '#kkkgkkkkkkkkkk#',
    '#kkgkkkgggggkkk#',
    '#kkkkkkkkkkkkkk#',
    '#kkkkkkkkkkkkkk#',
    '#kkkkkkkkkkkkkk#',
    '.##############.',
    '................',
    '................',
  ],
  mail: [
    '................',
    '................',
    '................',
    '################',
    '#aaaaaaaaaaaaaa#',
    '#a#aaaaaaaaaa#a#',
    '#aa#aaaaaaaa#aa#',
    '#aaa#aaaaaa#aaa#',
    '#aaaa#aaaa#aaaa#',
    '#aaaaa####aaaaa#',
    '#aaaaaaaaaaaaaa#',
    '#aaaaaaaaaaaaaa#',
    '################',
    '................',
    '................',
    '................',
  ],
  note: [
    '................',
    '..############..',
    '..#aaaaaaaaaa#..',
    '..#a########a#..',
    '..#aaaaaaaaaa#..',
    '..#a########a#..',
    '..#aaaaaaaaaa#..',
    '..#a######aaa#..',
    '..#aaaaaaaaaa#..',
    '..#aaaaaaaaaa#..',
    '..#aaaaaa#####..',
    '..#aaaaaa#aa#...',
    '..#aaaaaa#a#....',
    '..#########.....',
    '................',
    '................',
  ],
  people: [
    '................',
    '................',
    '...###....###...',
    '..#aaa#..#aaa#..',
    '..#aaa#..#aaa#..',
    '..#aaa#..#aaa#..',
    '...###....###...',
    '..#####..#####..',
    '.#aaaaa##aaaaa#.',
    '#aaaaaa##aaaaaa#',
    '#aaaaaa##aaaaaa#',
    '#aaaaaa##aaaaaa#',
    '#aaaaaa##aaaaaa#',
    '################',
    '................',
    '................',
  ],
  bomb: [
    '..........#.#...',
    '.........#.#....',
    '..........#.....',
    '.........#......',
    '........##......',
    '.......####.....',
    '.....########...',
    '....##oo######..',
    '...##o#########.',
    '...############.',
    '...############.',
    '...############.',
    '....##########..',
    '.....########...',
    '.......####.....',
    '................',
  ],
}

interface Props {
  name: IconName
  size?: number
  /** CSS colour for the icon's accent area */
  fill?: string
}

export function Icon({ name, size = 32, fill = 'var(--c3)' }: Props) {
  if (name === 'face') return <Portrait size={size} />
  const legend = { '#': 'var(--ink)', a: fill, o: 'var(--paper)', k: '#111111', g: '#8ff5c9' }
  return <PixelGrid rows={GRIDS[name]} legend={legend} size={size} />
}
