import { PixelGrid } from './PixelGrid'

// K ink, a accent (the fill prop), W white, S silver
const GRIDS = {
  dumbbell: [
    '................',
    '................',
    '................',
    '.KK..........KK.',
    'KaaK........KaaK',
    'KaaK........KaaK',
    'KaaKKKKKKKKKKaaK',
    'KaaKWWWWWWWWKaaK',
    'KaaKKKKKKKKKKaaK',
    'KaaK........KaaK',
    'KaaK........KaaK',
    '.KK..........KK.',
    '................',
    '................',
    '................',
    '................',
  ],
  shoe: [
    '................',
    '................',
    '................',
    '......KKKK......',
    '.....KaaaaK.....',
    '....KaaaaaK.....',
    '...KaaWaWaaKK...',
    '..KaaaaaaaaaaKK.',
    '.KaaaaaaaaaaaaaK',
    'KaaaaaaaaaaaaaaK',
    'KKKKKKKKKKKKKKKK',
    'KWWWWWWWWWWWWWWK',
    '.KKKKKKKKKKKKKK.',
    '................',
    '................',
    '................',
  ],
  goggles: [
    '................',
    '................',
    '................',
    '................',
    '.KKKKK....KKKKK.',
    'KaaaaaK..KaaaaaK',
    'KaWaaaKKKKaWaaaK',
    'KaaaaaK..KaaaaaK',
    '.KKKKK....KKKKK.',
    '................',
    '..KK...KK...KK..',
    '.K..K.K..K.K..K.',
    'K....K....K....K',
    '................',
    '................',
    '................',
  ],
  shuttle: [
    '................',
    '...K..K..K..K...',
    '...KWWKWWKWWK...',
    '...KWWKWWKWWK...',
    '....KWKWWKWK....',
    '....KWKWWKWK....',
    '.....KKWWKK.....',
    '.....KWWWWK.....',
    '......KKKK......',
    '.....KaaaaK.....',
    '.....KaaaaK.....',
    '......KaaK......',
    '.......KK.......',
    '................',
    '................',
    '................',
  ],
  book: [
    '................',
    '................',
    '.KKKKKKK.KKKKKK.',
    'KaaaaaaaKaaaaaaK',
    'KaWWWWWaKaWWWWaK',
    'KaaaaaaaKaaaaaaK',
    'KaWWWWWaKaWWWWaK',
    'KaaaaaaaKaaaaaaK',
    'KaWWWWWaKaWWWWaK',
    'KaaaaaaaKaaaaaaK',
    'KaaaaaaaKaaaaaaK',
    '.KKKKKKKKKKKKKK.',
    '................',
    '................',
    '................',
    '................',
  ],
  football: [
    '................',
    '.....KKKKKK.....',
    '...KKWWWWWWKK...',
    '..KWWWWKKWWWWK..',
    '.KWWWWKKKKWWWWK.',
    '.KWKWWKKKKWWKWK.',
    'KWKKWWWKKWWWKKWK',
    'KWKKWWWWWWWWKKWK',
    'KWWWWWWWWWWWWWWK',
    'KWWWWKKWWKKWWWWK',
    '.KWWKKKWWKKKWWK.',
    '.KWWWKKWWKKWWWK.',
    '..KWWWWWWWWWWK..',
    '...KKWWWWWWKK...',
    '.....KKKKKK.....',
    '................',
  ],
  mic: [
    '................',
    '......KKKK......',
    '.....KaaaaK.....',
    '.....KaWaaK.....',
    '.....KaaaaK.....',
    '.....KaaaaK.....',
    '...K.KaaaaK.K...',
    '...K..KKKK..K...',
    '...K........K...',
    '....K......K....',
    '.....KKKKKK.....',
    '.......KK.......',
    '.......KK.......',
    '.....KKKKKK.....',
    '................',
    '................',
  ],
  whisk: [
    '................',
    '......KKKK......',
    '.....K.KK.K.....',
    '....K..KK..K....',
    '....K.K..K.K....',
    '....K.K..K.K....',
    '....K.K..K.K....',
    '.....KK..KK.....',
    '......KKKK......',
    '.......KK.......',
    '......KaaK......',
    '......KaaK......',
    '......KaaK......',
    '......KaaK......',
    '.......KK.......',
    '................',
  ],
  palette: [
    '................',
    '.....KKKKKK.....',
    '...KKaaaaaaKK...',
    '..KaaWWaaaaaaK..',
    '.KaaaWWaaaKKaaK.',
    '.KaaaaaaaaKKaaK.',
    'KaaKKaaaaaaaaaaK',
    'KaaKKaaaaaaWWaaK',
    'KaaaaaaaaaaWWaaK',
    'KaaaaaKKKaaaaaK.',
    '.KaaaK...KaaaK..',
    '.KaaaaKKKaaaK...',
    '..KKaaaaaaKK....',
    '....KKKKKK......',
    '................',
    '................',
  ],
  ring: [
    '................',
    '.....KKKKKK.....',
    '...KKaaaaaaKK...',
    '..KaaKKKKKKaaK..',
    '.KaaK......KaaK.',
    '.KaK........KaK.',
    'KaaK........KaaK',
    'KaaK........KaaK',
    'KaaK........KaaK',
    'KaaK........KaaK',
    '.KaK........KaK.',
    '.KaaK......KaaK.',
    '..KaaKKKKKKaaK..',
    '...KKaaaaaaKK...',
    '.....KKKKKK.....',
    '................',
  ],
  mac: [
    '..KKKKKKKKKKKK..',
    '.KWWWWWWWWWWWWK.',
    '.KWKKKKKKKKKKWK.',
    '.KWKaaaaaaaaKWK.',
    '.KWKaaKaaKaaKWK.',
    '.KWKaaaaaaaaKWK.',
    '.KWKaKaaaaKaKWK.',
    '.KWKaaKKKKaaKWK.',
    '.KWKKKKKKKKKKWK.',
    '.KWWWWWWWWWWWWK.',
    '.KWWWWWWWKKKKWK.',
    '.KWWWWWWWWWWWWK.',
    '.KKKKKKKKKKKKKK.',
    '..KWWWWWWWWWWK..',
    '..KKKKKKKKKKKK..',
    '................',
  ],
  medal: [
    '...KKK....KKK...',
    '...KaaK..KaaK...',
    '....KaaKKaaK....',
    '.....KaaaaK.....',
    '......KKKK......',
    '.....KSSSSK.....',
    '....KSSSSSSK....',
    '...KSSSKKSSSK...',
    '...KSSKSSKSSK...',
    '...KSSSSKSSSK...',
    '...KSSSKSSSSK...',
    '...KSSKKKKSSK...',
    '....KSSSSSSK....',
    '.....KSSSSK.....',
    '......KKKK......',
    '................',
  ],
}

export type StickerName = keyof typeof GRIDS

export function Sticker({ name, size = 48, fill = 'var(--c4)' }: { name: StickerName; size?: number; fill?: string }) {
  const legend = { K: 'var(--ink)', a: fill, W: '#ffffff', S: '#d6d6d6' }
  return <PixelGrid rows={GRIDS[name]} legend={legend} size={size} />
}
